export const ADD_RECO = 'ADD_RECO';
export const ADD_RECO_SUCCESS = 'ADD_RECO_SUCCESS';
export const ADD_RECO_ERROR = 'ADD_RECO_ERROR';
export const EDIT_RECO = 'EDIT_RECO';
export const EDIT_RECO_SUCCESS = 'EDIT_RECO_SUCCESS';
export const REMOVE_RECO = 'REMOVE_RECO';
export const LOAD_RECOS_SUCCESS = 'LOAD_RECOS_SUCCESS';
export const UNLOAD_RECOS_SUCCESS = 'UNLOAD_RECOS_SUCCESS';
